/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.util.*;
import javax.swing.*;
import model.Tempat;

/**
 *
 * @author Project_MazeGame_175314080_175314103
 */
public class MazeGame extends javax.swing.JFrame {

    Tempat peta;
    File file;
    int level = 1;//Menentukan jumlah Level
    boolean bantu = false;//Untuk cheatButton

    String[] cheat1 = {"r 3", "d 3", "r 2", "d 1"};
    String[] cheat2 = {"r 1", "d 3", "r 2", "d 1", "r 2"};
    String[] cheat3 = {"u 1", "l 2", "u 3", "l 3"};
    //Cheat Pada Adventure

    ArrayList<String> cheat = new ArrayList<>();
    //Untuk menyimpan cheat

    public MazeGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        AboutDialog = new javax.swing.JDialog();
        tentangLabel = new javax.swing.JLabel();
        tentangTextArea = new java.awt.TextArea();
        tutupButton = new javax.swing.JButton();
        selPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        perintahText = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        restartButton = new javax.swing.JButton();
        cheatButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        adventureMenuItem = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        AdventureMenu = new javax.swing.JMenuItem();
        howToplayMenu = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        AboutDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AboutDialog.setFocusTraversalPolicyProvider(true);
        AboutDialog.setLocation(new java.awt.Point(569, 200));

        tentangLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tentangLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tentangLabel.setText("About Maze Game");

        tentangTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tentangTextArea.setEditable(false);
        tentangTextArea.setText("- How To Move\n  Untuk arah menggunakan \n  statment dibawah ini:\n  R\t= Right\n  L \t= Left\n  U \t= Up\n  D\t= Down\n\n  Untuk banyak langkah\n  menggunakan angka\n  sesuai kebutuhan\n  Contoh : R 5\n  Maka Player akan bergerak\n  ke Kanan sebanyak 5 langkah\n\n- Undo\n  Terdapat tombol Undo jika \n  Anda klik maka akan kembali\n  ke posisi sebelumnya\n\n- Restart\n  Mengembalikan posisi Player \n  ke tempat awal\n\n- Cheat\n  Dapat digunakan saat \n  menggunakan Adventure\n");

        tutupButton.setText("Tutup");
        tutupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AboutDialogLayout = new javax.swing.GroupLayout(AboutDialog.getContentPane());
        AboutDialog.getContentPane().setLayout(AboutDialogLayout);
        AboutDialogLayout.setHorizontalGroup(
            AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutDialogLayout.createSequentialGroup()
                .addGroup(AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutDialogLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(tentangLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tutupButton)))
                    .addGroup(AboutDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tentangTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AboutDialogLayout.setVerticalGroup(
            AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tentangLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(tentangTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tutupButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selPanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        selPanel.setPreferredSize(new java.awt.Dimension(500, 300));

        javax.swing.GroupLayout selPanelLayout = new javax.swing.GroupLayout(selPanel);
        selPanel.setLayout(selPanelLayout);
        selPanelLayout.setHorizontalGroup(
            selPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        selPanelLayout.setVerticalGroup(
            selPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Perintah");

        perintahText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perintahTextActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        undoButton.setText("Undo");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        restartButton.setText("Restart");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        cheatButton.setText("Cheat");
        cheatButton.setEnabled(bantu);
        cheatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheatButtonActionPerformed(evt);
            }
        });

        adventureMenuItem.setText("File");
        adventureMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adventureMenuItemActionPerformed(evt);
            }
        });

        openMenuItem.setText("Open Map");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        adventureMenuItem.add(openMenuItem);

        AdventureMenu.setText("Adventure");
        AdventureMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdventureMenuActionPerformed(evt);
            }
        });
        adventureMenuItem.add(AdventureMenu);

        howToplayMenu.setText("About");
        howToplayMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToplayMenuActionPerformed(evt);
            }
        });
        adventureMenuItem.add(howToplayMenu);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        adventureMenuItem.add(exitMenuItem);

        jMenuBar1.add(adventureMenuItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perintahText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(undoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(restartButton)
                .addGap(18, 18, 18)
                .addComponent(cheatButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(selPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(selPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(perintahText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton)
                    .addComponent(undoButton)
                    .addComponent(restartButton)
                    .addComponent(cheatButton))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(585, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        selPanel.removeAll();
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = jFileChooser1.getSelectedFile();
            peta = new Tempat(file);
            selPanel.add(peta);
            peta.setSize(peta.getLebar() + 50, peta.getTinggi() + 50);
            //setelah diset panel sel, kita letakkan posisi peta Mazegame
            int lebar = selPanel.getWidth();
            int tinggi = selPanel.getHeight();
            //mendapatkan titik koordinat x,y
            int x = (lebar - peta.getWidth()) / 2;
            int y = (tinggi - peta.getHeight()) / 2;
            peta.setLocation(x, y);

        }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            peta.Gerak(perintahText.getText());
            perintahText.setText("");
            selesaiPeta();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Baca Peta Terlebih Dahulu !", "Peringatan", 0);
        }

    }//GEN-LAST:event_okButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        peta.undo();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        peta.restartPlayer();
    }//GEN-LAST:event_restartButtonActionPerformed

    private void perintahTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perintahTextActionPerformed
        peta.Gerak(perintahText.getText());
        perintahText.setText("");
        selesaiPeta();
    }//GEN-LAST:event_perintahTextActionPerformed

    private void peta2() {

        selPanel.removeAll();
        cheat.clear();
        peta = new Tempat(new File("Peta1.txt"));
        loadcheat(cheat2);
        selPanel.add(peta);
        peta.setSize(peta.getLebar() + 50, peta.getTinggi() + 50);
        int lebar = selPanel.getWidth();
        int tinggi = selPanel.getHeight();
        int x = (lebar - peta.getWidth()) / 2;
        int y = (tinggi - peta.getHeight()) / 2;
        peta.setLocation(x, y);
    }

    private void peta3() {
        selPanel.removeAll();
        cheat.clear();
        peta = new Tempat(new File("Peta2.txt"));
        loadcheat(cheat3);
        selPanel.add(peta);
        peta.setSize(peta.getLebar() + 50, peta.getTinggi() + 50);
        //setelah diset panel sel, kita letakkan posisi peta Mazegame
        int lebar = selPanel.getWidth();
        int tinggi = selPanel.getHeight();
        //mendapatkan titik koordinat x,y
        int x = (lebar - peta.getWidth()) / 2;
        int y = (tinggi - peta.getHeight()) / 2;
        peta.setLocation(x, y);
    }

    public void loadcheat(String[] cheata) {
        cheat.addAll(Arrays.asList(cheata));
    }

    private void selesaiPeta() {
        if (peta.isComplete()) {
            JOptionPane.showMessageDialog(null, "Selamat Anda Berhasil Menyelesaikan\nGame Maze Game ini");
            selPanel.removeAll();
            System.exit(0);
        }
    }

    private void selesaiLevel() {
        if (peta.isComplete()) {
            switch (level) {
                case 1:
                    cheat.clear();
                    JOptionPane.showMessageDialog(null, "Level 1 Selesai");
                    peta.hapus();
                    selPanel.removeAll();
                    peta2();
                    JOptionPane.showMessageDialog(null, "Level 2");
                    level++;
                    break;
                case 2:
                    JOptionPane.showMessageDialog(null, "Level  2 Selesai");
                    peta.hapus();
                    selPanel.removeAll();
                    peta3();
                    JOptionPane.showMessageDialog(null, "Level 3");
                    level++;
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Tamat\nTerima Kasih Telah mencoba\n^.^");
                    selPanel.removeAll();
                    System.exit(0);
            }
        }
    }
    private void howToplayMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToplayMenuActionPerformed
        AboutDialog.setSize(250, 400);
        AboutDialog.setVisible(true);
    }//GEN-LAST:event_howToplayMenuActionPerformed

    private void AdventureMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdventureMenuActionPerformed
        JOptionPane.showMessageDialog(null, "Jika Anda membuka peta ini maka \nanda akan melewati 3 rintangan");
        bantu = true;
        loadcheat(cheat1);
        cheatButton.setEnabled(bantu);
        peta = new Tempat(new File("Peta.txt"));
        selPanel.add(peta);
        peta.setSize(peta.getLebar() + 50, peta.getTinggi() + 50);
        int lebar = selPanel.getWidth();
        int tinggi = selPanel.getHeight();
        int x = (lebar - peta.getWidth()) / 2;
        int y = (tinggi - peta.getHeight()) / 2;
        peta.setLocation(x, y);
        JOptionPane.showMessageDialog(null, "Level 1");
    }//GEN-LAST:event_AdventureMenuActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void tutupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupButtonActionPerformed
        AboutDialog.dispose();
    }//GEN-LAST:event_tutupButtonActionPerformed

    private void adventureMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adventureMenuItemActionPerformed

    }//GEN-LAST:event_adventureMenuItemActionPerformed

    private void cheatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheatButtonActionPerformed
        for (int i = 0; i < cheat.size(); i++) {
            peta.Gerak(cheat.get(i));
            selesaiLevel();
        }
    }//GEN-LAST:event_cheatButtonActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MazeGame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> {
            new MazeGame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AboutDialog;
    private javax.swing.JMenuItem AdventureMenu;
    private javax.swing.JMenu adventureMenuItem;
    private javax.swing.JButton cheatButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem howToplayMenu;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton okButton;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JTextField perintahText;
    private javax.swing.JButton restartButton;
    private javax.swing.JPanel selPanel;
    private javax.swing.JLabel tentangLabel;
    private java.awt.TextArea tentangTextArea;
    private javax.swing.JButton tutupButton;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables
}
